export const DATA = {
  men: [
    {
      id: 1,
      title: "Women's tracksuit Q109",
      file: "menclouthes.png",
      price: 35,
      discount: 0,
    },
    {
      id: 2,
      title: "Women's tracksuit Q109",
      file: "menclouthes.png",
      price: 35,
      discount: 70,
    },
    {
      id: 3,
      title: "Women's tracksuit Q109",
      file: "menclouthes.png",
      price: 35,
      discount: 0,
    },
    {
      id: 4,
      title: "Women's tracksuit Q109",
      file: "menclouthes.png",
      price: 35,
      discount: 0,
    },
    {
      id: 5,
      title: "Women's tracksuit Q109",
      file: "menclouthes.png",
      price: 35,
      discount: 0,
    },
    {
      id: 6,
      title: "Women's tracksuit Q109",
      file: "menclouthes.png",
      price: 35,
      discount: 0,
    },
    {
      id: 7,
      title: "Women's tracksuit Q109",
      file: "menclouthes.png",
      price: 35,
      discount: 0,
    },
    {
      id: 8,
      title: "Women's tracksuit Q109",
      file: "menclouthes.png",
      price: 35,
      discount: 0,
    },
  ],
  women: [
    {
      id: 1,
      title: "Women's tracksuit Q109",
      file: "shirt.png",
      price: 50,
      discount: 0,
    },
    {
      id: 2,
      title: "Women's tracksuit Q109",
      file: "shirt.png",
      price: 50,
      discount: 0,
    },
    {
      id: 3,
      title: "Women's tracksuit Q109",
      file: "shirt.png",
      price: 50,
      discount: 0,
    },
    {
      id: 4,
      title: "Women's tracksuit Q109",
      file: "shirt.png",
      price: 50,
      discount: 0,
    },
    {
      id: 5,
      title: "Women's tracksuit Q109",
      file: "shirt.png",
      price: 50,
      discount: 0,
    },
    {
      id: 6,
      title: "Women's tracksuit Q109",
      file: "shirt.png",
      price: 50,
      discount: 50,
    },
    {
      id: 7,
      title: "Women's tracksuit Q109",
      file: "shirt.png",
      price: 50,
      discount: 0,
    },
    {
      id: 8,
      title: "Women's tracksuit Q109",
      file: "shirt.png",
      price: 50,
      discount: 0,
    },
  ],
};

export const MENU = [
  { id: 1, path: "About Us" },
  { id: 2, path: "men" },
  { id: 3, path: "women" },
  { id: 4, path: "Beauty" },
  { id: 5, path: "Accessories" },
  { id: 6, path: "Blog" },
  { id: 7, path: "Contact" },
];
