export const ACTION_TYPES = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
  DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',
  REMOVE_FROM_PRODUCT: 'REMOVE_FROM_PRODUCT',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',
  // FETCH_PRODUCT_ID: 'FETCH_PRODUCT_ID',
  SHOW_ERROR: 'SHOW_ERROR',
  HIDE_ERROR: 'HIDE_ERROR',
};